# Configuración del proyecto SonarQube para Backend
sonar.host.url=http://localhost:9000

# Identificadores de proyecto
sonar.projectKey=pilas-backend1
sonar.projectName=Pilas! - Backend
sonar.projectVersion=1.0.0

# Orígenes de código y exclusiones
sonar.sources=src
sonar.exclusions=node_modules/**, dist/**, coverage/**, src/sockets/**, src/config/**, src/scripts/**, src/server.js, scratch/**

# Idioma y codificación
sonar.sourceEncoding=UTF-8

# Cobertura de pruebas (LCOV)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
