name: SonarCloud Job

on:
  workflow_call:

jobs:
  sonar:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Desactivar clonación superficial (shallow clone) para análisis de SonarCloud

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=JoseSanmartin1999_Pilas--backend
            -Dsonar.organization=josesanmartin1999
            -Dsonar.sources=src
            -Dsonar.host.url=https://sonarcloud.io

      - name: SonarCloud Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
