name: SonarCloud Job

on:
  workflow_call:

jobs:
  sonar:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Desactivar clonación superficial (shallow clone) para análisis de SonarCloud

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            "-Dsonar.projectKey=josesanmartin1999_Pilas--backend"
            "-Dsonar.organization=josesanmartin1999"
            "-Dsonar.sources=src"
            "-Dsonar.host.url=https://sonarcloud.io"
            "-Dsonar.verbose=true"
